puf_platform_homepage:
    path:     /
    defaults: { _controller: PUFPlatformBundle:Default:index }
add_pays:
    path:     /add-pays
    defaults: { _controller: PUFPlatformBundle:Default:create }
catalogue_route:
    path: /catalogue
    defaults: {_controller: PUFPlatformBundle:Default:showcatalogue}
chercher_route:
    path: /chercher
    defaults: {_controller: PUFPlatformBundle:Default:chercher}